In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [8]:
data = {
    'age': [25, 30, 35, 40],
    'income': [50000, 60000, 70000, 80000],
    'city': ['New York', 'Los Angeles', 'Chicago', 'New York']
}


In [9]:
data

{'age': [25, 30, 35, 40],
 'income': [50000, 60000, 70000, 80000],
 'city': ['New York', 'Los Angeles', 'Chicago', 'New York']}

In [10]:
df = pd.DataFrame(data)
df

age  income         city
0   25   50000     New York
1   30   60000  Los Angeles
2   35   70000      Chicago
3   40   80000     New York

# Standard scalar - converting the data to mean=0 and SD = 1

In [11]:
scaler = StandardScaler()
scaler.fit(df[['age', 'income']])


StandardScaler()

In [12]:
scaler.mean_

array([3.25e+01, 6.50e+04])

In [13]:
scaler.var_

array([3.125e+01, 1.250e+08])

In [14]:
scaled_income = scaler.transform(df[['age', 'income']])

In [15]:
pd.DataFrame(scaled_income, columns = scaler.get_feature_names_out())

age    income
0 -1.341641 -1.341641
1 -0.447214 -0.447214
2  0.447214  0.447214
3  1.341641  1.341641

# Min Max Scaler

In [16]:
minmax = MinMaxScaler()
minmax.fit(df[['age', 'income']])

MinMaxScaler()

In [17]:
minmax_income = minmax.transform(df[['age', 'income']])

In [18]:
pd.DataFrame(minmax_income, columns = minmax.get_feature_names_out())

age    income
0  0.000000  0.000000
1  0.333333  0.333333
2  0.666667  0.666667
3  1.000000  1.000000

# One Hot Encoder

In [25]:
transformer=ColumnTransformer(transformers =[('onehot', OneHotEncoder(handle_unknown='ignore'),['city'])],remainder='passthrough')

In [26]:
ohe_output = transformer.fit_transform(df)

In [29]:
transformer.fit_transform(df)

array([[0.0e+00, 0.0e+00, 1.0e+00, 2.5e+01, 5.0e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 6.0e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 7.0e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 4.0e+01, 8.0e+04]])

In [30]:
ohe_output = transformer.fit_transform(df)

In [31]:
pd.DataFrame(ohe_output, columns = transformer.get_feature_names_out())

onehot__city_Chicago  onehot__city_Los Angeles  onehot__city_New York  \
0                   0.0                       0.0                    1.0   
1                   0.0                       1.0                    0.0   
2                   1.0                       0.0                    0.0   
3                   0.0                       0.0                    1.0   

   remainder__age  remainder__income  
0            25.0            50000.0  
1            30.0            60000.0  
2            35.0            70000.0  
3            40.0            80000.0